"""update tables

Revision ID: 2da2991a4c11
Revises: 28ffc858c684
Create Date: 2024-02-29 00:18:24.897162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2da2991a4c11'
down_revision: Union[str, None] = '28ffc858c684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'initial_balance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.create_unique_constraint(None, 'accounts', ['account_id'])
    op.create_unique_constraint(None, 'categories', ['category_id'])
    op.alter_column('transactions', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('transactions', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('transactions', 'notes',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'transactions', ['transaction_id'])
    op.alter_column('users', 'registered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'registered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'transactions', type_='unique')
    op.alter_column('transactions', 'notes',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('transactions', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('transactions', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'accounts', type_='unique')
    op.alter_column('accounts', 'initial_balance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###
